key-name = "firstpem"
hosted-zone = "erkanbaran.me"
git-user = "Erkanbarann"
repo-name = "car-rental-system-with-terraform"
dbname = "araba_kiralama"
dbuser = "admin"
dbsifre = "admin123" # Consider using a secret manager (e.g., AWS Secrets Manager, HashiCorp Vault) for sensitive data.
app-name = "araba_kiralama"
domain-name = "erkanbaran.me"